TEMPLATE_BASIC_INFORMATION_ID = "e6749abb-c487-4b6c-98e0-8637f2bc1931"

MGID_APPLY_TEMPLATE_ID = "e6749abb-c487-4b6c-98e0-8637f2bc1932"

WORD_TEMPLATE_ID = "e6749abb-c487-4b6c-98e0-8637f2bc1933"

UNSEARCHABLE_TEMPLATE_ID_SET = (TEMPLATE_BASIC_INFORMATION_ID, WORD_TEMPLATE_ID)

SAMPLE_TEMPLATE_ID = "e6749abb-c487-4b6c-98e0-8637f2bc1934"

SOURCE_TEMPLATE_ID = "e6749abb-c487-4b6c-98e1-8637f2bc1934"

DERIVED_TEMPLATE_ID = "e6749abb-c487-4b6c-98e0-8637f2bc1936"

TEMPLATE_PRESET = {
    "sample": SAMPLE_TEMPLATE_ID,
    "source": SOURCE_TEMPLATE_ID,
    "derived": DERIVED_TEMPLATE_ID,
    "application": "",
}

TEMPLATE_RECURSIVE_LAYER = 2

REVIEW_STATUS_DRAFT = "draft"

REVIEW_STATUS_WAITING_REVIEW = "waiting_review"

REVIEW_STATUS_PASSED_REVIEW_WAITING_PUBLISHED = "passed_review_waiting_published"

REVIEW_STATUS_PASSED_REVIEW = "passed_review"

REVIEW_STATUS_PASSED_REVIEW_PREVIEW = "passed_review_preview"

REVIEW_STATUS_PASSED_REVIEW_WAITING_REVIEW = "passed_review_waiting_review"

REVIEW_STATUS_REJECTED = "rejected"

REVIEW_STATUS_DEPRECATED = "deprecated"

CURRENT_USER = "me"

INPUT_FLAG = "input_flag"

REQUIRED_FLAG = "required"

MGID_CUSTOM_FIELD_TITLE = "MGID自定义部分"

NOT_FOUND_CONTENT = b"Not found"

EXCLUDETEMPLATES = (
    TEMPLATE_BASIC_INFORMATION_ID,
    MGID_APPLY_TEMPLATE_ID,
    WORD_TEMPLATE_ID,
    SAMPLE_TEMPLATE_ID,
    SOURCE_TEMPLATE_ID,
    DERIVED_TEMPLATE_ID,
)

ADMIN_LEVEL = {"super_admin": 0, "admin": 1, "normal": 2}
